services:
  apps:
    image: nom_de_votre_image:tag
    container_name: vault-microservice
    depends_on:
      - vault-dev
    environment:
      VAULT_ADDR: http://vault-dev:8200
      ROLE_ID: <<WRITE_YOUR_ROLE_ID>>
      SECRET_ID: <<WRITE_YOUR_SECRET_ID>>
    ports:
      - "8000:8000"
